// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM98-yo6Bx9BhU1nzzfRpFOnBLZG5eZdA',
    appId: '1:695603879536:web:89d27413f009c2b8fddeb5',
    messagingSenderId: '695603879536',
    projectId: 'nom-nom-4f1e0',
    authDomain: 'nom-nom-4f1e0.firebaseapp.com',
    storageBucket: 'nom-nom-4f1e0.firebasestorage.app',
    measurementId: 'G-GZM19RM2YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqRuGOMql8uN1EOUy_HREploB0tVT5dFA',
    appId: '1:695603879536:android:a089588dab84f624fddeb5',
    messagingSenderId: '695603879536',
    projectId: 'nom-nom-4f1e0',
    storageBucket: 'nom-nom-4f1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17DgTzx-M-s0zLkZ0vJxs73NoNoICNuU',
    appId: '1:695603879536:ios:46e6cc888ef64f6afddeb5',
    messagingSenderId: '695603879536',
    projectId: 'nom-nom-4f1e0',
    storageBucket: 'nom-nom-4f1e0.firebasestorage.app',
    iosBundleId: 'com.example.cooker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB17DgTzx-M-s0zLkZ0vJxs73NoNoICNuU',
    appId: '1:695603879536:ios:46e6cc888ef64f6afddeb5',
    messagingSenderId: '695603879536',
    projectId: 'nom-nom-4f1e0',
    storageBucket: 'nom-nom-4f1e0.firebasestorage.app',
    iosBundleId: 'com.example.cooker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM98-yo6Bx9BhU1nzzfRpFOnBLZG5eZdA',
    appId: '1:695603879536:web:1268980a46e54a4afddeb5',
    messagingSenderId: '695603879536',
    projectId: 'nom-nom-4f1e0',
    authDomain: 'nom-nom-4f1e0.firebaseapp.com',
    storageBucket: 'nom-nom-4f1e0.firebasestorage.app',
    measurementId: 'G-FTF34EQQ4T',
  );
}
